blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/whytcard-dev/Whytcard_discuss/discussions
    about: Veuillez poser vos questions et y répondre ici.
  - name: Documentation Source (Anglais)
    url: https://github.com/whytcard-dev/Whytcard_discuss/tree/main/EN
    about: Consultez notre documentation source pour plus d'informations.
  - name: Signaler un problème de sécurité
    url: https://github.com/whytcard-dev/Whytcard_discuss/security/policy
    about: Veuillez consulter notre politique de sécurité pour signaler des vulnérabilités. 